/**
 * Energy Units
 *
 * SI base unit: Joule (J)
 */

import { Dimension } from '../dimensions.js';

export const energyUnits = [
  {
    id: 'J',
    name: 'Joule',
    symbol: 'J',
    htmlSymbol: 'J',
    dimension: Dimension.ENERGY,
    factor: 1,
    offset: 0,
    system: 'SI',
    isBase: true,
    tags: ['chemistry', 'physics', 'thermodynamics'],
  },
  {
    id: 'kJ',
    name: 'Kilojoule',
    symbol: 'kJ',
    htmlSymbol: 'kJ',
    dimension: Dimension.ENERGY,
    factor: 1000,
    offset: 0,
    system: 'SI',
    isBase: false,
    tags: ['chemistry', 'thermodynamics'],
  },
  {
    id: 'MJ',
    name: 'Megajoule',
    symbol: 'MJ',
    htmlSymbol: 'MJ',
    dimension: Dimension.ENERGY,
    factor: 1e6,
    offset: 0,
    system: 'SI',
    isBase: false,
    tags: ['engineering'],
  },
  {
    id: 'cal',
    name: 'Calorie (thermochemical)',
    symbol: 'cal',
    htmlSymbol: 'cal',
    dimension: Dimension.ENERGY,
    factor: 4.184,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['chemistry', 'thermodynamics'],
  },
  {
    id: 'kcal',
    name: 'Kilocalorie',
    symbol: 'kcal',
    htmlSymbol: 'kcal',
    dimension: Dimension.ENERGY,
    factor: 4184,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['chemistry', 'nutrition'],
  },
  {
    id: 'Cal',
    name: 'Calorie (food)',
    symbol: 'Cal',
    htmlSymbol: 'Cal',
    dimension: Dimension.ENERGY,
    factor: 4184,  // Same as kcal
    offset: 0,
    system: 'common',
    isBase: false,
    tags: ['nutrition'],
  },
  {
    id: 'eV',
    name: 'Electronvolt',
    symbol: 'eV',
    htmlSymbol: 'eV',
    dimension: Dimension.ENERGY,
    factor: 1.602176634e-19,
    offset: 0,
    system: 'atomic',
    isBase: false,
    tags: ['physics', 'atomic'],
  },
  {
    id: 'keV',
    name: 'Kiloelectronvolt',
    symbol: 'keV',
    htmlSymbol: 'keV',
    dimension: Dimension.ENERGY,
    factor: 1.602176634e-16,
    offset: 0,
    system: 'atomic',
    isBase: false,
    tags: ['physics', 'nuclear'],
  },
  {
    id: 'MeV',
    name: 'Megaelectronvolt',
    symbol: 'MeV',
    htmlSymbol: 'MeV',
    dimension: Dimension.ENERGY,
    factor: 1.602176634e-13,
    offset: 0,
    system: 'atomic',
    isBase: false,
    tags: ['physics', 'nuclear'],
  },
  {
    id: 'BTU',
    name: 'British Thermal Unit',
    symbol: 'BTU',
    htmlSymbol: 'BTU',
    dimension: Dimension.ENERGY,
    factor: 1055.06,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['engineering', 'hvac'],
  },
  {
    id: 'Wh',
    name: 'Watt-hour',
    symbol: 'Wh',
    htmlSymbol: 'Wh',
    dimension: Dimension.ENERGY,
    factor: 3600,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['electrical'],
  },
  {
    id: 'kWh',
    name: 'Kilowatt-hour',
    symbol: 'kWh',
    htmlSymbol: 'kWh',
    dimension: Dimension.ENERGY,
    factor: 3600000,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['electrical', 'everyday'],
  },
  {
    id: 'L_atm',
    name: 'Liter-atmosphere',
    symbol: 'L·atm',
    htmlSymbol: 'L·atm',
    dimension: Dimension.ENERGY,
    factor: 101.325,
    offset: 0,
    system: 'common',
    isBase: false,
    tags: ['chemistry', 'gas-laws'],
  },
];

export default energyUnits;
