/**
 * Length Units
 *
 * SI base unit: Meter (m)
 */

import { Dimension } from '../dimensions.js';

export const lengthUnits = [
  {
    id: 'm',
    name: 'Meter',
    symbol: 'm',
    htmlSymbol: 'm',
    dimension: Dimension.LENGTH,
    factor: 1,
    offset: 0,
    system: 'SI',
    isBase: true,
    tags: ['physics'],
  },
  {
    id: 'km',
    name: 'Kilometer',
    symbol: 'km',
    htmlSymbol: 'km',
    dimension: Dimension.LENGTH,
    factor: 1000,
    offset: 0,
    system: 'SI',
    isBase: false,
    tags: ['everyday'],
  },
  {
    id: 'cm',
    name: 'Centimeter',
    symbol: 'cm',
    htmlSymbol: 'cm',
    dimension: Dimension.LENGTH,
    factor: 0.01,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['laboratory', 'everyday'],
  },
  {
    id: 'mm',
    name: 'Millimeter',
    symbol: 'mm',
    htmlSymbol: 'mm',
    dimension: Dimension.LENGTH,
    factor: 0.001,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['laboratory'],
  },
  {
    id: 'um',
    name: 'Micrometer',
    symbol: 'μm',
    htmlSymbol: 'μm',
    dimension: Dimension.LENGTH,
    factor: 0.000001,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['microscopy'],
  },
  {
    id: 'nm',
    name: 'Nanometer',
    symbol: 'nm',
    htmlSymbol: 'nm',
    dimension: Dimension.LENGTH,
    factor: 1e-9,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['spectroscopy', 'nanotechnology'],
  },
  {
    id: 'pm',
    name: 'Picometer',
    symbol: 'pm',
    htmlSymbol: 'pm',
    dimension: Dimension.LENGTH,
    factor: 1e-12,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['atomic'],
  },
  {
    id: 'A',
    name: 'Angstrom',
    symbol: 'Å',
    htmlSymbol: 'Å',
    dimension: Dimension.LENGTH,
    factor: 1e-10,
    offset: 0,
    system: 'atomic',
    isBase: false,
    tags: ['crystallography', 'atomic'],
  },
  {
    id: 'in',
    name: 'Inch',
    symbol: 'in',
    htmlSymbol: 'in',
    dimension: Dimension.LENGTH,
    factor: 0.0254,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['everyday'],
  },
  {
    id: 'ft',
    name: 'Foot',
    symbol: 'ft',
    htmlSymbol: 'ft',
    dimension: Dimension.LENGTH,
    factor: 0.3048,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['everyday'],
  },
  {
    id: 'yd',
    name: 'Yard',
    symbol: 'yd',
    htmlSymbol: 'yd',
    dimension: Dimension.LENGTH,
    factor: 0.9144,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['everyday'],
  },
  {
    id: 'mi',
    name: 'Mile',
    symbol: 'mi',
    htmlSymbol: 'mi',
    dimension: Dimension.LENGTH,
    factor: 1609.344,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['everyday'],
  },
];

export default lengthUnits;
