/**
 * Mass Units
 *
 * SI base unit: Kilogram (kg)
 */

import { Dimension } from '../dimensions.js';

export const massUnits = [
  {
    id: 'kg',
    name: 'Kilogram',
    symbol: 'kg',
    htmlSymbol: 'kg',
    dimension: Dimension.MASS,
    factor: 1,
    offset: 0,
    system: 'SI',
    isBase: true,
    tags: ['chemistry', 'physics'],
  },
  {
    id: 'g',
    name: 'Gram',
    symbol: 'g',
    htmlSymbol: 'g',
    dimension: Dimension.MASS,
    factor: 0.001,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['chemistry', 'laboratory'],
  },
  {
    id: 'mg',
    name: 'Milligram',
    symbol: 'mg',
    htmlSymbol: 'mg',
    dimension: Dimension.MASS,
    factor: 0.000001,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['chemistry', 'laboratory', 'pharmaceutical'],
  },
  {
    id: 'ug',
    name: 'Microgram',
    symbol: 'μg',
    htmlSymbol: 'μg',
    dimension: Dimension.MASS,
    factor: 1e-9,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['biochemistry', 'laboratory'],
  },
  {
    id: 'ng',
    name: 'Nanogram',
    symbol: 'ng',
    htmlSymbol: 'ng',
    dimension: Dimension.MASS,
    factor: 1e-12,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['biochemistry'],
  },
  {
    id: 't',
    name: 'Metric Ton',
    symbol: 't',
    htmlSymbol: 't',
    dimension: Dimension.MASS,
    factor: 1000,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['industrial'],
  },
  {
    id: 'lb',
    name: 'Pound',
    symbol: 'lb',
    htmlSymbol: 'lb',
    dimension: Dimension.MASS,
    factor: 0.45359237,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['everyday'],
  },
  {
    id: 'oz',
    name: 'Ounce',
    symbol: 'oz',
    htmlSymbol: 'oz',
    dimension: Dimension.MASS,
    factor: 0.028349523125,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['everyday'],
  },
  {
    id: 'amu',
    name: 'Atomic Mass Unit',
    symbol: 'u',
    htmlSymbol: 'u',
    dimension: Dimension.MASS,
    factor: 1.66053906660e-27,
    offset: 0,
    system: 'atomic',
    isBase: false,
    tags: ['chemistry', 'nuclear'],
  },
];

export default massUnits;
