/**
 * Pressure Units
 *
 * SI base unit: Pascal (Pa)
 */

import { Dimension } from '../dimensions.js';

export const pressureUnits = [
  {
    id: 'Pa',
    name: 'Pascal',
    symbol: 'Pa',
    htmlSymbol: 'Pa',
    dimension: Dimension.PRESSURE,
    factor: 1,
    offset: 0,
    system: 'SI',
    isBase: true,
    tags: ['chemistry', 'physics'],
  },
  {
    id: 'kPa',
    name: 'Kilopascal',
    symbol: 'kPa',
    htmlSymbol: 'kPa',
    dimension: Dimension.PRESSURE,
    factor: 1000,
    offset: 0,
    system: 'SI',
    isBase: false,
    tags: ['chemistry', 'physics'],
  },
  {
    id: 'MPa',
    name: 'Megapascal',
    symbol: 'MPa',
    htmlSymbol: 'MPa',
    dimension: Dimension.PRESSURE,
    factor: 1e6,
    offset: 0,
    system: 'SI',
    isBase: false,
    tags: ['engineering'],
  },
  {
    id: 'bar',
    name: 'Bar',
    symbol: 'bar',
    htmlSymbol: 'bar',
    dimension: Dimension.PRESSURE,
    factor: 100000,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['chemistry', 'meteorology'],
  },
  {
    id: 'mbar',
    name: 'Millibar',
    symbol: 'mbar',
    htmlSymbol: 'mbar',
    dimension: Dimension.PRESSURE,
    factor: 100,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['meteorology'],
  },
  {
    id: 'atm',
    name: 'Atmosphere',
    symbol: 'atm',
    htmlSymbol: 'atm',
    dimension: Dimension.PRESSURE,
    factor: 101325,
    offset: 0,
    system: 'common',
    isBase: false,
    tags: ['chemistry', 'gas-laws'],
  },
  {
    id: 'mmHg',
    name: 'Millimeters of Mercury',
    symbol: 'mmHg',
    htmlSymbol: 'mmHg',
    dimension: Dimension.PRESSURE,
    factor: 133.322387415,
    offset: 0,
    system: 'common',
    isBase: false,
    tags: ['chemistry', 'gas-laws', 'medical'],
  },
  {
    id: 'torr',
    name: 'Torr',
    symbol: 'Torr',
    htmlSymbol: 'Torr',
    dimension: Dimension.PRESSURE,
    factor: 133.322368421,  // Exactly 1/760 atm
    offset: 0,
    system: 'common',
    isBase: false,
    tags: ['chemistry', 'vacuum'],
  },
  {
    id: 'psi',
    name: 'Pounds per Square Inch',
    symbol: 'psi',
    htmlSymbol: 'psi',
    dimension: Dimension.PRESSURE,
    factor: 6894.757293168,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['engineering'],
  },
  {
    id: 'inHg',
    name: 'Inches of Mercury',
    symbol: 'inHg',
    htmlSymbol: 'inHg',
    dimension: Dimension.PRESSURE,
    factor: 3386.389,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['meteorology', 'aviation'],
  },
];

export default pressureUnits;
