/**
 * Volume Units
 *
 * SI base unit: Cubic meter (m³)
 */

import { Dimension } from '../dimensions.js';

export const volumeUnits = [
  {
    id: 'm3',
    name: 'Cubic Meter',
    symbol: 'm³',
    htmlSymbol: 'm<sup>3</sup>',
    dimension: Dimension.VOLUME,
    factor: 1,
    offset: 0,
    system: 'SI',
    isBase: true,
    tags: ['physics'],
  },
  {
    id: 'L',
    name: 'Liter',
    symbol: 'L',
    htmlSymbol: 'L',
    dimension: Dimension.VOLUME,
    factor: 0.001,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['chemistry', 'gas-laws'],
  },
  {
    id: 'mL',
    name: 'Milliliter',
    symbol: 'mL',
    htmlSymbol: 'mL',
    dimension: Dimension.VOLUME,
    factor: 0.000001,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['chemistry', 'laboratory'],
  },
  {
    id: 'uL',
    name: 'Microliter',
    symbol: 'μL',
    htmlSymbol: 'μL',
    dimension: Dimension.VOLUME,
    factor: 1e-9,
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['biochemistry', 'laboratory'],
  },
  {
    id: 'cm3',
    name: 'Cubic Centimeter',
    symbol: 'cm³',
    htmlSymbol: 'cm<sup>3</sup>',
    dimension: Dimension.VOLUME,
    factor: 0.000001,  // Same as mL
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['chemistry', 'laboratory'],
  },
  {
    id: 'dm3',
    name: 'Cubic Decimeter',
    symbol: 'dm³',
    htmlSymbol: 'dm<sup>3</sup>',
    dimension: Dimension.VOLUME,
    factor: 0.001,  // Same as L
    offset: 0,
    system: 'metric',
    isBase: false,
    tags: ['chemistry'],
  },
  {
    id: 'gal',
    name: 'Gallon (US)',
    symbol: 'gal',
    htmlSymbol: 'gal',
    dimension: Dimension.VOLUME,
    factor: 0.003785411784,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['everyday'],
  },
  {
    id: 'qt',
    name: 'Quart (US)',
    symbol: 'qt',
    htmlSymbol: 'qt',
    dimension: Dimension.VOLUME,
    factor: 0.000946352946,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['everyday'],
  },
  {
    id: 'pt',
    name: 'Pint (US)',
    symbol: 'pt',
    htmlSymbol: 'pt',
    dimension: Dimension.VOLUME,
    factor: 0.000473176473,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['everyday'],
  },
  {
    id: 'fl_oz',
    name: 'Fluid Ounce (US)',
    symbol: 'fl oz',
    htmlSymbol: 'fl oz',
    dimension: Dimension.VOLUME,
    factor: 0.0000295735295625,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['everyday'],
  },
  {
    id: 'in3',
    name: 'Cubic Inch',
    symbol: 'in³',
    htmlSymbol: 'in<sup>3</sup>',
    dimension: Dimension.VOLUME,
    factor: 0.000016387064,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['engineering'],
  },
  {
    id: 'ft3',
    name: 'Cubic Foot',
    symbol: 'ft³',
    htmlSymbol: 'ft<sup>3</sup>',
    dimension: Dimension.VOLUME,
    factor: 0.028316846592,
    offset: 0,
    system: 'imperial',
    isBase: false,
    tags: ['engineering'],
  },
];

export default volumeUnits;
