# Generated by Django 4.2.11 on 2025-12-11 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("SI", "SI (International System)"),
                            ("imperial", "Imperial/US"),
                            ("custom", "Custom"),
                        ],
                        default="SI",
                        help_text="Unit system preset",
                        max_length=10,
                    ),
                ),
                (
                    "preferred_units",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map of dimension to preferred unit ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit Preferences",
                "verbose_name_plural": "Unit Preferences",
            },
        ),
    ]
