# Generated by Django 4.2.11 on 2024-03-31 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="This calculator's name", max_length=72)),
                ('description', models.TextField(help_text='The calculator reference the user may hide/show')),
                ('component', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='CalculatorCategory',
            fields=[
                ('type', models.CharField(choices=[('GSLW', 'Gas Laws'), ('SOLN', 'Solutions'), ('MISC', 'Miscellaneous'), ('STCH', 'Stoichiometry'), ('THRM', 'Thermodynamics'), ('CNVR', 'Unit Conversions'), ('ELCT', 'Electrochemistry'), ('NCLR', 'Nuclear Chemistry')], help_text='The calculator classification', max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=72)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculators.calculator')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.FloatField(null=True)),
                ('name', models.CharField(help_text="The variable's name", max_length=64)),
                ('unit', models.CharField(help_text="The variable's unit", max_length=16)),
                ('symbol', models.CharField(help_text="The variable's symbol", max_length=16)),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculators.equation')),
            ],
        ),
        migrations.AddField(
            model_name='calculator',
            name='calc_category',
            field=models.ForeignKey(help_text='Type of Calculator', on_delete=django.db.models.deletion.PROTECT, to='calculators.calculatorcategory'),
        ),
    ]
