# Generated by Django 4.2.11 on 2024-03-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equation',
            name='calculator',
        ),
        migrations.AddField(
            model_name='calculator',
            name='equation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='calculators.equation'),
        ),
    ]
