# Generated by Django 4.2.11 on 2024-03-31 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_remove_equation_calculator_calculator_equation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculator',
            old_name='description',
            new_name='information',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='component',
        ),
        migrations.AlterField(
            model_name='calculator',
            name='calc_category',
            field=models.CharField(choices=[('GSLW', 'Gas Laws'), ('SOLN', 'Solutions'), ('MISC', 'Miscellaneous'), ('STCH', 'Stoichiometry'), ('THRM', 'Thermodynamics'), ('CNVR', 'Unit Conversions'), ('ELCT', 'Electrochemistry'), ('NCLR', 'Nuclear Chemistry')], default='MISC', help_text='Calculator Category', max_length=4),
        ),
        migrations.AlterField(
            model_name='variable',
            name='equation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Variables', to='calculators.equation'),
        ),
        migrations.DeleteModel(
            name='CalculatorCategory',
        ),
    ]
