# Generated by Django 4.2.11 on 2024-03-31 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0003_rename_description_calculator_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='equation',
        ),
        migrations.AddField(
            model_name='equation',
            name='variables',
            field=models.ManyToManyField(to='calculators.variable'),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='equation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculators.equation'),
        ),
    ]
