# Generated by Django 4.2.11 on 2024-04-10 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0006_remove_calculator_equation_equation_latex_repr'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='equation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculators.equation'),
        ),
        migrations.AddField(
            model_name='variable',
            name='symbol_u',
            field=models.CharField(help_text="The variable's symbol (user view)", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='symbol',
            field=models.CharField(help_text="The variable's symbol (internal)", max_length=16),
        ),
    ]
