# Generated by Django 4.2.11 on 2024-04-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0007_calculator_equation_variable_symbol_u_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='val',
        ),
        migrations.AddField(
            model_name='variable',
            name='value',
            field=models.FloatField(default=None, help_text="The variable's value", null=True),
        ),
    ]
