# Generated by Django 4.2.11 on 2025-12-06 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calculators", "0012_remove_variable_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteEquation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="calculators.equation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_equations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite Equation",
                "verbose_name_plural": "Favorite Equations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="favoriteequation",
            constraint=models.UniqueConstraint(
                fields=("user", "equation"), name="unique_user_equation_favorite"
            ),
        ),
    ]
