# Generated by Django 4.2.11 on 2025-12-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculators", "0014_calculator_registry_and_favorites_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculator",
            name="calc_category",
            field=models.CharField(
                choices=[
                    ("GSLW", "Gas Laws"),
                    ("THRM", "Thermodynamics"),
                    ("KNTC", "Kinetics"),
                    ("SOLN", "Solutions"),
                    ("ELEC", "Electrochemistry"),
                    ("MISC", "Miscellaneous"),
                ],
                default="MISC",
                help_text="Calculator category",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="calculator",
            name="name",
            field=models.CharField(
                help_text='Display name (e.g., "Avogadro\'s Law")', max_length=72
            ),
        ),
    ]
